location: francecentral
name: tg-container-group
properties:
  containers:
    - name: tightdb
      properties:
        image: mariadb:latest
        environmentVariables:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: mydb
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: user
        volumeMounts:
          - name: azure-file-share
            mountPath: /var/lib/mysql
        ports:
          - port: 3306
        resources:
          requests:
            cpu: 1
            memoryInGb: 1

    - name: tightgroups
      properties:
        image: insiares/tightgroups:latest
        ports:
          - port: 8501
          - port: 8000
        environmentVariables:
          - name: METEO_USERNAME
            value: PLACEHOLDER_METEO_USERNAME
          - name: METEO_PWD
            value: PLACEHOLDER_METEO_PASSWORD
          - name: BACKEND_URL
            value: PLACEHOLDER_BACKEND_URL
          - name: JWT_KEY
            value: PLACEHOLDER_JWT_SECRET
          - name: DATABASE_URL
            value: PLACEHOLDER_DATABASE_URL
        volumeMounts:
          - name: azure-file-share
            mountPath: /mnt/asf
        resources:
          requests:
           # cpu: 0.5
           # memoryInGb: 1
        
    - name: kuma
      properties:
        image: louislam/uptime-kuma:latest
      #  environmentVariables:
       #   - name: DB_TYPE
        #    value: sqlite
        #  - name: DB_SQLITE_FILE
        #    value: /data/kuma.db
        #  - name: UPKUMA_PORT
         #   value: "3001"
        ports:
          - port: 3001
        resources:
          requests:
            cpu: 0.25
            memoryInGb: 0.8
        volumeMounts:
          - name: azure-file-share
            mountPath: app/data/

  osType: Linux
  volumes:
  - name: azure-file-share
    azureFile:
      sharename: tightafs
      storageAccountName: PLACEHOLDER_SHAREACCOUNT
      storageAccountKey: PLACEHOLDER_SHAREKEY
  restartPolicy: Always
  ipAddress:
    type: public
    dnsNameLabel: tightgroups
    ports:
      - port: 8501
      - port: 3001
