
CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Setups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    gear VARCHAR(255),
    ammo VARCHAR(255),
    position VARCHAR(255),
    drills VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    setup_id INT,
    file_path VARCHAR(255) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (setup_id) REFERENCES Setups(id) ON DELETE SET NULL
);

CREATE TABLE Scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_id INT,
    score_value DECIMAL(5, 2),
    group_size DECIMAL(5, 2),
    calculation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (image_id) REFERENCES Images(id) ON DELETE CASCADE
);
