# [theme]
# primaryColor="#39603a"
# backgroundColor="#545e5c"
# secondaryBackgroundColor="#565b62"
# textColor="#262730"


[theme]
# Main colors
primaryColor = "#89b4fa"  # Catppuccin blue
backgroundColor = "#1e1e2e"  # Base color
secondaryBackgroundColor = "#313244"  # Surface0
textColor = "#cdd6f4"  # Text
font = "monospace"

[server]
address = "0.0.0.0"
port = "8501"
enableCORS = false
enableXsrfProtection = false
